name: 'Semantic Release'
description: 'Evaluate next release version'
inputs:
  branches:
    description: 'Set of release branches separated by newline'
    required: false
    default: |
      +([0-9])?(.{+([0-9]),x}).x
      master
      next
      next-major
      { "name": "alpha", "prerelease": true }
      { "name": "beta", "prerelease": true }
  plugins:
    description: Set of plugins to use
    required: false
    default: |
      @semantic-release/commit-analyzer
      @semantic-release/release-notes-generator
  tagFormat:
    description: The Git tag format used by semantic-release to identify releases
    required: false
    default: 'v${version}'
outputs:
  version:
    description: "Next release version"
  notes:
    description: "Release notes"
  type:
    description: "Release type (minor | major | patch)"
  tag:
    description: "Tag name"
  channel:
    description: "Channel name"
  name:
    description: "Release name"
runs:
  using: 'node16'
  main: 'index.js'
