on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run action
        uses: ./
        id: release
      # Use the output from the `hello` step
      - name: Get the output
        run: |
          echo "Version: ${{ steps.release.outputs.version }}"
          echo "Tag: ${{ steps.release.outputs.tag }}"
          echo "Name: ${{ steps.release.outputs.name }}"
          echo "Notes: ${{ steps.release.outputs.notes }}"
          echo "Type: ${{ steps.release.outputs.type }}"
          echo "Channel: ${{ steps.release.outputs.channel }}"